---
title: "Datenaufbereitung"
author: "g3r!t"
date: "4 5 2021"
output: powerpoint_presentation
---

```{r import libraries}
# Import needed libraries
library(ggplot2)
library(readr)
library(lubridate)
library(dplyr)
library(forcats)
library(RCurl)
library(readxl)
```


```{r import turnover data}
#import turnover data
umsatzdaten <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/umsatzdaten_gekuerzt.csv")

# Convert ware group number into ware group name
# 1=Brot, 2=Broetchen, 3=Crossaint, 4=Konditorei, 5=Kuchen, 6=Saisonbrot
Warengruppen <- c("Brot", "Brötchen", "Crossaint", "Konditorei", "Kuchen", "Saisonbrot")
for (e in as.numeric(row.names(umsatzdaten)))
  umsatzdaten$Warengruppe[e] <- Warengruppen[as.numeric(umsatzdaten$Warengruppe[e])]
```
```{r import kiwo data}
#import kiwo data
kiwo <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/kiwo.csv")
```

```{r import weather data}
#import weather data
wetterdaten <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/wetter.csv")

#import weathercodes
#URL weather codes https://www.seewetter-kiel.de/seewetter/daten_symbole.htm
#wind speed in knots[kn = sm/h = (km/h)/1.852]
wettercodes <- read_delim("https://raw.githubusercontent.com/g3r1t/EDSML-Projekt/main/Wettercodes.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

# Change column-name of "Code" to "Wettercode"
colnames(wettercodes)[colnames(wettercodes) == "Code"] <- "Wettercode"

#windchill berechnen (https://de.wikipedia.org/wiki/Windchill)
for (e in as.numeric(row.names(wetterdaten)))
  wetterdaten$Windchill[e] <- 13.12 + 0.6215 * wetterdaten$Temperatur[e] - 11.37 * 
                              (wetterdaten$Windgeschwindigkeit[e]*1.852)**0.16 + 
                              0.3965*wetterdaten$Temperatur[e] * 
                              (wetterdaten$Windgeschwindigkeit[e]*1.852)**0.16
```
```{r import overnight stay data}
months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
years <- as.character(13:19)

for (e in years)
  if (e == "13") {
    JahrMonat <- paste(e, months, sep = "")
  } else {
    a <- paste(e, months, sep = "")
    JahrMonat <- c(JahrMonat, a)
  }


Uebernachtungen <- ""
for (e in JahrMonat){
  print(e)
  filename <- paste("G_IV_1-m",e,"_SH.xlsx", sep = "")
  url <- paste("https://www.statistik-nord.de/fileadmin/Dokumente/Statistische_Berichte/industrie__handel_und_dienstl/G_IV_1_m_S/", filename, sep = "")
  if (url.exists(url=url)) {
    filedest <- paste("sheets/", filename, sep = "")
    curl::curl_download(url, filedest)
    xls <- read_excel(filedest, sheet = "T1_1")
    Uebernachtungen <- c(Uebernachtungen, xls[4][xls[1] == "02 Kiel"])
  } else {
      filename <- paste("G_IV_1-m",e,"_SH-.xlsx", sep = "")
      url <- paste("https://www.statistik-nord.de/fileadmin/Dokumente/Statistische_Berichte/industrie__handel_und_dienstl/G_IV_1_m_S/", filename, sep = "")
      if (!url.exists(url=url)) {
        filename <- paste("G_IV_1_m_S_",e,".xlsx", sep = "")
        url <- paste("https://www.statistik-nord.de/fileadmin/Dokumente/Statistische_Berichte/industrie__handel_und_dienstl/G_IV_1_m_S/", filename, sep = "")
        if (!url.exists(url=url)) {
          filename <- paste("G_IV_1_m",e,"_SH.xlsx", sep = "")
          url <- paste("https://www.statistik-nord.de/fileadmin/Dokumente/Statistische_Berichte/industrie__handel_und_dienstl/G_IV_1_m_S/", filename, sep = "")
        }
      }
    filedest <- paste("sheets/", filename, sep = "")
    curl::curl_download(url, filedest)
    xls <- read_excel(filedest, sheet = "T1_1")
    Uebernachtungen <- c(Uebernachtungen, xls[4][xls[1] == "02 Kiel"])
  }
}
Uebernachtungen <- as.numeric(Uebernachtungen[-1])
```

```{r merge datasets}
#merge datasets
KiwoUndUmsatz <- full_join(umsatzdaten, kiwo, by = "Datum")
Alles <- full_join(KiwoUndUmsatz, wetterdaten, by = "Datum")
AllesUndWettercodes <- left_join(Alles, wettercodes, by = "Wettercode")
```